### ISSUE TITLE
`PicassoImage` doesn't scale correctly when `Modifier.aspectRatio()` is used

### ISSUE THREAD

**Issue by alexjlockwood** [chrisbanes/accompanist#118]
I have a sample app that I was working on for a blog post. 

In the `picasso-bug` branch, I use a `PicassoImage` like this ([link to code](https://github.com/alexjlockwood/adp-contact-list-compose/blob/alex/picasso-bug/app/src/main/java/com/alexjlockwood/contactlistcompose/ui/ContactCard.kt#L61-L66)):

```
    PicassoImage(
        data = imageUrl,
        modifier = modifier.aspectRatio(16f / 9f),
        fadeIn = true,
        contentScale = ContentScale.Crop,
    )
```

![screencap-1602620231](https://user-images.githubusercontent.com/1380747/95911725-b16d2200-0d56-11eb-8063-2818d4fd3e52.png)

I do not see this same behavior with `CoilImage` however. On the `master` branch, I am using [this code](https://github.com/alexjlockwood/adp-contact-list-compose/blob/master/app/src/main/java/com/alexjlockwood/contactlistcompose/ui/ContactCard.kt#L61-L66):

```
    CoilImage(
        data = imageUrl,
        modifier = modifier.aspectRatio(16f / 9f),
        fadeIn = true,
        contentScale = ContentScale.Crop,
    )
```

![screencap-1602620122](https://user-images.githubusercontent.com/1380747/95912014-14f74f80-0d57-11eb-8464-0ba5bb2a62c5.png)

**Comment by chrisbanes** [comment]
This is an interesting one. 

So the issue is that I'm calling `Picasso.get(...).resize(composableSize).onlyScaleDown()`, which scales the bitmap to to fill the bounds (ignoring aspect ratio). This is very different to Coil's handling, which never changes the aspect ratio (much, much better imo).

Now, we two options: `centerCrop()` or `centerInside()`, and neither are perfect. 

- `centerCrop()` is the right solution if you're using `ContentScale.Crop` (it does the same thing), but it breaks the other `ContentScale`s.
- `centerInside()` maintains aspect ratio, but scales down. So images might be scaled smaller than the composable, and then scaled back up via the `ContentScale` which will look bad.
- Ideally I want a `centerOutside()`, which will scale the image so that both dimensions are `>=` requested bounds (i.e. it covers the bounds), similar to Coil's [`Scale.FILL`](https://coil-kt.github.io/coil/api/coil-base/coil.size/-scale/-f-i-l-l/)


I think I'll have to go with the correct solution: `centerInside()`.

**Comment by alexjlockwood** [comment]
thanks for the quick fix chris!
